version: '3.8'

services:
  web:
    build: .
    container_name: asthra-ctf
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
